[package]
name = "lib"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
num = "0.4.0"

[profile.release]
lto = "thin"
# Tell `rustc` to optimize for small code size.
opt-level = "s"